### ISSUE TITLE
Remove <h3> tag around participant's name

### ISSUE THREAD

**Issue by Warpsmith** [woocommerce/sensei-course-participants#19]
Hello!
Provided this plugin isn't dead:

At line 123 in the file  _sensei-course-participants/includes/class-sensei-course-participants-widget.php_  is this:

`$learner_name = '<h3 itemprop="name" class="learner-name">' . esc_html( $display_name ) . '</h3>' . "\n";`

In most themes, the Header3 tag is used for widget headers, so the content of this widget will likely look unreasonably wonkey as a default. 

Also it seems quite odd to use header elements for a list of names. 
Can it be changed to paragraph elements, or some other element more suitable for a list of names, or at least a H4 or H5?

**Comment by danjjohnson** [comment]
Valid point, will get that changed in the next update. Thanks!

**Comment by donnapep** [comment]
I don't think we need to wrap any element around the name as it's already wrapped inside an anchor tag.

**Comment by donnapep** [comment]
@Warpsmith The `<h3>` has been changed to a `<span>` and is ready for testing in the [Course Participants 2.0 beta](https://github.com/woocommerce/sensei-course-participants/releases/download/version%2F2.0.0-beta.1/sensei-course-participants-2.0.0-beta.1.zip), if you're still using this plugin. 🙂
