### ISSUE TITLE
Add a filter on the participant's profile link

### ISSUE THREAD

**Issue by Warpsmith** [woocommerce/sensei-course-participants#20]
It is quite nice to use Buddypress in combination with Sensei. And [Buddypress for Sensei](https://wordpress.org/plugins/sensei-buddypress/) is a good solution to accomplish that combo.

But it would also be nice to use this widget, but it doesn't link to the Buddypress profile pages.
The links should look like this:
http://example.com/members/peter/
but instead they are like:
http://example.com/learner/peter/ 

If it was possible to filter the output of this widget, it would be an very easy fix. So... can a filter be added?

**Comment by danjjohnson** [comment]
Yes, we can probably add a filter in the next release. Thanks for the suggestion.

**Comment by donnapep** [comment]
@Warpsmith The filter `sensei_course_participants_profile_url` has been added and is ready for testing in the [Course Participants 2.0 beta](https://github.com/woocommerce/sensei-course-participants/releases/download/version%2F2.0.0-beta.1/sensei-course-participants-2.0.0-beta.1.zip), if you're still using this plugin. 🙂
