### ISSUE TITLE
Counter position is between course progress parts.

### ISSUE THREAD

**Issue by renatho** [woocommerce/sensei-course-participants#72]
### Steps to Reproduce

1. Create a legacy course (without new blocks).
2. Go to the course page in the frontend.

### What I Expected

- To not be between the course progress parts. Maybe before or after.

### What Happened Instead

- Check that the course participants' counter is between the 2 progress parts.

### PHP / WordPress / Sensei Course Participants / Sensei LMS version

PHP 7 / WP 5.5 / Course Participants 2.0.1 / Sensei LMS 3.6.0

### Screenshot / Video

<img width="612" alt="Screen Shot 2020-11-13 at 19 21 23" src="https://user-images.githubusercontent.com/876340/99126780-999eed00-25e5-11eb-8da1-d7346612fe10.png">

### Context / Source

Probably we just need to update the hook priority. Check https://github.com/Automattic/sensei/blob/master/includes/class-sensei-course.php#L3610 (`Sensei_Course::add_legacy_course_hooks`).

**Comment by donnapep** [comment]
In order to be consistent with how it displays on the course page when the user is not enrolled in the course, we should show it above the _Currently completed x lessons of y in total_ message.
